id: I99A1832D
legacy_id: P000313
ocr_import_info:
  bdrc_scan_id: W1KG12061
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T15:03:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:18:45.890485+00:00'
last_modified: 2022-08-31 11:18:53.581000
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12061
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12061
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་རྡོར་ཐུགས་ཀྱི་སྙིང་ཁུའི་སྐོར།
  author: རྭ་ཁྲོ་གཏེར་སྟོན་ཨོ་རྒྱན་འགྲོ་འདུལ་ཀུན་འདུས་གླིང་པ།
statistics: null
quality: null
bases:
  I1KG12065:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12065
      total_pages: 562
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12065.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
