id: P000313
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12061
  title: ཕྱག་རྡོར་ཐུགས་ཀྱི་སྙིང་ཁུའི་སྐོར།
  author: ''
  volumes:
    c42f1e6c613541b1878464842d6bb424:
      image_group_id: I1KG12065
      title: Volume 1 of phyag rdor thugs kyi snying khu'i skor/
      volume_number: 1
      total_pages: 562
      base_file: v001.txt
